# XcodeGen project configuration for GoodBook
name: GoodBook
options:
  minimumXcodeGenVersion: 2.37.0
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.cory.GoodBook
    INFOPLIST_FILE: GoodBook/Info.plist
    SWIFT_VERSION: 5.9
packages: {}

targets:
  GoodBook:
    type: application
    platform: iOS
    sources:
      - path: GoodBook
      - path: AppResources
        type: folder
        buildPhase: resources
    settings:
      base:
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGNING_ALLOWED[sdk=iphonesimulator*]: NO
        CODE_SIGNING_REQUIRED[sdk=iphonesimulator*]: NO
        CODE_SIGN_IDENTITY[sdk=iphonesimulator*]: "-"
    scheme:
      testTargets:
        - GoodBookTests
        - GoodBookUITests
      gatherCoverageData: true
      coverageTargets:
        - GoodBook

  GoodBookTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      # Exclude the Bibles fixtures from normal file references to avoid flattening
      # and duplicate resource names in the test bundle. We'll add them back below
      # as a folder reference so the subdirectory structure (Bibles/<TRANSLATION>/)
      # is preserved inside the .xctest bundle.
      - path: GoodBookTests
        excludes:
          - "**/Fixtures/Bibles/**"
      # Add Bibles fixtures as a folder reference (blue folder) so resources are
      # copied with their directory hierarchy (prevents 'John.json' name collisions).
      - path: GoodBookTests/Fixtures/Bibles
        type: folder
    dependencies:
      - target: GoodBook
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cory.GoodBookTests

  GoodBookUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: GoodBookUITests
    dependencies:
      - target: GoodBook
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cory.GoodBookUITests
