name: Update README build version

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-readme-build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compute short SHA and commit URL
        run: |
          SHORT_SHA=$(git rev-parse --short=7 "$GITHUB_SHA")
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          REPO_URL="https://github.com/${GITHUB_REPOSITORY}"
          echo "COMMIT_URL=${REPO_URL}/commit/${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Update README build version section
        run: |
          set -euo pipefail
          tmp_file=$(mktemp)
          awk -v sha="${SHORT_SHA}" -v url="${COMMIT_URL}" '
            BEGIN{in_block=0}
            /<!-- build-version: start -->/ {
              print;
              print "Latest: [" sha "](" url ")";
              in_block=1; next
            }
            /<!-- build-version: end -->/ { in_block=0 }
            { if (!in_block) print }
          ' README.md > "$tmp_file"
          mv "$tmp_file" README.md

      - name: Create pull request with README update
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs(readme): update build version to ${{ env.SHORT_SHA }} [skip ci]"
          title: "docs(readme): update build version to ${{ env.SHORT_SHA }}"
          body: |
            Automated update of README build version.
            - Commit: ${{ env.SHORT_SHA }}
            - Source workflow: ${{ github.workflow }} (#${{ github.run_number }})
          branch: "ci/update-readme-build"
          delete-branch: true
          add-paths: |
            README.md

